package main

import (
	"testing"
)

func TestInsertHeader_shortWithFrontmatter(t *testing.T) {
	input := "---\ntitle: Test\n---\n\n# Hello\n\nWorld.\n"
	want := "---\ntitle: Test\n---\n\n<!-- litprompt src/prompt.md -->\n\n# Hello\n\nWorld.\n"
	got := insertHeader(input, "short", "src/prompt.md")
	if got != want {
		t.Errorf("insertHeader short with frontmatter:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestInsertHeader_fullWithFrontmatter(t *testing.T) {
	input := "---\ntitle: Test\n---\n\n# Hello\n\nWorld.\n"
	want := "---\ntitle: Test\n---\n\n<!-- Generated by litprompt from src/prompt.md. Do not edit. -->\n\n# Hello\n\nWorld.\n"
	got := insertHeader(input, "full", "src/prompt.md")
	if got != want {
		t.Errorf("insertHeader full with frontmatter:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestInsertHeader_shortNoFrontmatter(t *testing.T) {
	input := "# Hello\n\nWorld.\n"
	want := "<!-- litprompt src/prompt.md -->\n\n# Hello\n\nWorld.\n"
	got := insertHeader(input, "short", "src/prompt.md")
	if got != want {
		t.Errorf("insertHeader short no frontmatter:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestInsertHeader_emptyContent(t *testing.T) {
	got := insertHeader("", "short", "src/prompt.md")
	want := "<!-- litprompt src/prompt.md -->\n"
	if got != want {
		t.Errorf("insertHeader empty:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestInsertHeader_noMode(t *testing.T) {
	input := "# Hello\n"
	got := insertHeader(input, "", "src/prompt.md")
	if got != input {
		t.Errorf("insertHeader no mode should be passthrough:\ngot:  %q\nwant: %q", got, input)
	}
}

func TestInsertHeader_invalidMode(t *testing.T) {
	input := "# Hello\n"
	got := insertHeader(input, "invalid", "src/prompt.md")
	if got != input {
		t.Errorf("insertHeader invalid mode should be passthrough:\ngot:  %q\nwant: %q", got, input)
	}
}
