package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tgvashworth/litprompt/internal/build"
)

func writeTestFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func mustRead(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}

func TestInsertHeader_shortWithFrontmatter(t *testing.T) {
	input := "---\ntitle: Test\n---\n\n# Hello\n\nWorld.\n"
	want := "---\ntitle: Test\n---\n\n<!-- litprompt src/prompt.md -->\n\n# Hello\n\nWorld.\n"
	got := insertHeader(input, "short", "src/prompt.md")
	if got != want {
		t.Errorf("insertHeader short with frontmatter:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestInsertHeader_fullWithFrontmatter(t *testing.T) {
	input := "---\ntitle: Test\n---\n\n# Hello\n\nWorld.\n"
	want := "---\ntitle: Test\n---\n\n<!-- Generated by litprompt from src/prompt.md. Do not edit. -->\n\n# Hello\n\nWorld.\n"
	got := insertHeader(input, "full", "src/prompt.md")
	if got != want {
		t.Errorf("insertHeader full with frontmatter:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestInsertHeader_shortNoFrontmatter(t *testing.T) {
	input := "# Hello\n\nWorld.\n"
	want := "<!-- litprompt src/prompt.md -->\n\n# Hello\n\nWorld.\n"
	got := insertHeader(input, "short", "src/prompt.md")
	if got != want {
		t.Errorf("insertHeader short no frontmatter:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestInsertHeader_emptyContent(t *testing.T) {
	got := insertHeader("", "short", "src/prompt.md")
	want := "<!-- litprompt src/prompt.md -->\n"
	if got != want {
		t.Errorf("insertHeader empty:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestInsertAfterFrontmatter(t *testing.T) {
	cases := []struct{ name, content, want string }{
		{
			name:    "frontmatter with trailing newline",
			content: "---\nname: X\n---\nbody\n",
			want:    "---\nname: X\n---\n\nLINE\nbody\n",
		},
		{
			// Regression: frontmatter ending at EOF without a final newline must
			// still be detected, so the line lands after it (not prepended above).
			name:    "frontmatter at EOF, no trailing newline",
			content: "---\nname: X\n---",
			want:    "---\nname: X\n---\nLINE\n",
		},
		{
			name:    "no frontmatter",
			content: "# body\n",
			want:    "LINE\n\n# body\n",
		},
		{
			name:    "empty content",
			content: "",
			want:    "LINE\n",
		},
	}
	for _, c := range cases {
		if got := insertAfterFrontmatter(c.content, "LINE"); got != c.want {
			t.Errorf("%s:\ngot:  %q\nwant: %q", c.name, got, c.want)
		}
	}
}

func TestInsertHeader_noMode(t *testing.T) {
	input := "# Hello\n"
	got := insertHeader(input, "", "src/prompt.md")
	if got != input {
		t.Errorf("insertHeader no mode should be passthrough:\ngot:  %q\nwant: %q", got, input)
	}
}

func TestInsertHeader_invalidMode(t *testing.T) {
	input := "# Hello\n"
	got := insertHeader(input, "invalid", "src/prompt.md")
	if got != input {
		t.Errorf("insertHeader invalid mode should be passthrough:\ngot:  %q\nwant: %q", got, input)
	}
}

func TestResolveOutputPath_singleFileToDir(t *testing.T) {
	srcDir := t.TempDir()
	outDir := t.TempDir()
	inputFile := srcDir + "/prompt.md"
	os.WriteFile(inputFile, []byte("# test\n"), 0o644)

	got, err := resolveOutputPath(inputFile, inputFile, outDir)
	if err != nil {
		t.Fatal(err)
	}
	want := outDir + "/prompt.md"
	if got != want {
		t.Errorf("resolveOutputPath single file to dir:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestResolveOutputPath_singleFileToTrailingSlash(t *testing.T) {
	srcDir := t.TempDir()
	inputFile := srcDir + "/prompt.md"
	os.WriteFile(inputFile, []byte("# test\n"), 0o644)

	// Trailing slash on a non-existent dir — should still map filename into it
	got, err := resolveOutputPath(inputFile, inputFile, "/tmp/nonexistent-out/")
	if err != nil {
		t.Fatal(err)
	}
	want := "/tmp/nonexistent-out/prompt.md"
	if got != want {
		t.Errorf("resolveOutputPath single file to trailing slash:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestResolveOutputPath_singleFileToFile(t *testing.T) {
	srcDir := t.TempDir()
	inputFile := srcDir + "/prompt.md"
	os.WriteFile(inputFile, []byte("# test\n"), 0o644)

	got, err := resolveOutputPath(inputFile, inputFile, "out.md")
	if err != nil {
		t.Fatal(err)
	}
	if got != "out.md" {
		t.Errorf("resolveOutputPath to file:\ngot:  %q\nwant: %q", got, "out.md")
	}
}

// --- config-driven build (runBuildFromConfig) ---

func TestRunBuildFromConfig_glob_siblingOutput_withHeader(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	writeTestFile(t, "plugins/data/skills/query/SKILL.src.md", "# query\n")
	writeTestFile(t, "plugins/data/skills/chart/SKILL.src.md", "# chart\n")
	writeTestFile(t, "litprompt.yaml", `builds:
  - source: plugins/*/skills/*/SKILL.src.md
    output: SKILL.md
    header: full
`)

	if err := runBuildFromConfig(build.Options{}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	for _, name := range []string{"query", "chart"} {
		out := mustRead(t, filepath.Join("plugins/data/skills", name, "SKILL.md"))
		if !strings.Contains(out, "# "+name) {
			t.Errorf("%s output missing content: %q", name, out)
		}
		if !strings.Contains(out, "Generated by litprompt") {
			t.Errorf("%s output missing header: %q", name, out)
		}
	}
}

func TestRunBuildFromConfig_directoryMode(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	writeTestFile(t, "src/a.md", "# a\n")
	writeTestFile(t, "src/sub/b.md", "# b\n")
	writeTestFile(t, "litprompt.yaml", `builds:
  - source: src/
    output: out/
`)

	if err := runBuildFromConfig(build.Options{}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if got := mustRead(t, "out/a.md"); !strings.Contains(got, "# a") {
		t.Errorf("out/a.md missing content: %q", got)
	}
	if got := mustRead(t, "out/sub/b.md"); !strings.Contains(got, "# b") {
		t.Errorf("out/sub/b.md missing content: %q", got)
	}
}

func TestRunBuildFromConfig_keepGoingOnError(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	writeTestFile(t, "src/good.md", "# good\n")
	writeTestFile(t, "src/bad.md", "@[missing](./does-not-exist.md)\n")
	writeTestFile(t, "litprompt.yaml", `builds:
  - source: src/
    output: out/
`)

	err := runBuildFromConfig(build.Options{})
	if err == nil {
		t.Fatal("expected error from failing build, got nil")
	}
	if !strings.Contains(err.Error(), "failed") {
		t.Errorf("error should mention failure: %v", err)
	}
	if _, statErr := os.Stat("out/good.md"); statErr != nil {
		t.Errorf("good output should still be written despite a sibling failure: %v", statErr)
	}
	if _, statErr := os.Stat("out/bad.md"); statErr == nil {
		t.Errorf("bad output should NOT exist")
	}
}

func TestRunBuildFromConfig_noConfig_errors(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	err := runBuildFromConfig(build.Options{})
	if err == nil {
		t.Fatal("expected error when no litprompt.yaml exists, got nil")
	}
	if !strings.Contains(err.Error(), "litprompt.yaml") {
		t.Errorf("error should mention litprompt.yaml: %v", err)
	}
}

func TestRunBuildFromConfig_mixedShapes(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	writeTestFile(t, "single.md", "# single\n")
	writeTestFile(t, "src/a.md", "# a\n")
	writeTestFile(t, "skills/foo/SKILL.src.md", "# foo skill\n")
	writeTestFile(t, "litprompt.yaml", `builds:
  - source: single.md
    output: dist/single-out.md
  - source: src/
    output: out/
  - source: skills/*/SKILL.src.md
    output: SKILL.md
`)

	if err := runBuildFromConfig(build.Options{}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	for _, p := range []string{"dist/single-out.md", "out/a.md", "skills/foo/SKILL.md"} {
		if _, err := os.Stat(p); err != nil {
			t.Errorf("expected %s to exist: %v", p, err)
		}
	}
}

func TestRunBuildFromConfig_explicitConfigInOtherDir(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	// Config and source live in envs/, not the cwd. Paths in the config are
	// relative to the config's directory, so the output should land there too.
	writeTestFile(t, "envs/agent.md", "# agent\n")
	writeTestFile(t, "envs/litprompt.prod.yaml", `builds:
  - source: agent.md
    output: dist/agent.md
`)

	configPath = "envs/litprompt.prod.yaml"
	defer func() { configPath = "" }()

	if err := runBuildFromConfig(build.Options{}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Output resolves relative to the config dir (envs/), not the cwd.
	if got := mustRead(t, filepath.Join(dir, "envs/dist/agent.md")); !strings.Contains(got, "# agent") {
		t.Errorf("envs/dist/agent.md missing content: %q", got)
	}
	if _, err := os.Stat(filepath.Join(dir, "dist/agent.md")); err == nil {
		t.Error("output should not be written relative to cwd")
	}
}

func TestRunBuildFromConfig_explicitConfigMissing_errors(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	configPath = "litprompt.prod.yaml"
	defer func() { configPath = "" }()

	err := runBuildFromConfig(build.Options{})
	if err == nil {
		t.Fatal("expected error for missing named config, got nil")
	}
	if !strings.Contains(err.Error(), "litprompt.prod.yaml") {
		t.Errorf("error should name the missing config: %v", err)
	}
}

func TestRunBuild_configFlagWithSourceArg_errors(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	writeTestFile(t, "prompt.md", "# hi\n")

	configPath = "litprompt.prod.yaml"
	defer func() { configPath = "" }()

	err := runBuild(nil, []string{"prompt.md"})
	if err == nil {
		t.Fatal("expected error combining --config with a source argument, got nil")
	}
	if !strings.Contains(err.Error(), "--config") {
		t.Errorf("error should mention --config: %v", err)
	}
}

// --- config-driven check (runCheckFromConfig) ---

func TestRunCheckFromConfig_allValid(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	writeTestFile(t, "src/a.md", "# a\n")
	writeTestFile(t, "src/sub/b.md", "# b\n")
	writeTestFile(t, "litprompt.yaml", `builds:
  - source: src/
    output: out/
`)

	if err := runCheckFromConfig(build.Options{}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Check must not write any output — only validate.
	if _, err := os.Stat("out"); err == nil {
		t.Error("check should not have written output directory")
	}
}

func TestRunCheckFromConfig_reportsFailures(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	writeTestFile(t, "src/good.md", "# good\n")
	writeTestFile(t, "src/bad.md", "@[missing](./does-not-exist.md)\n")
	writeTestFile(t, "litprompt.yaml", `builds:
  - source: src/
    output: out/
`)

	err := runCheckFromConfig(build.Options{})
	if err == nil {
		t.Fatal("expected error from failing entry, got nil")
	}
	if !strings.Contains(err.Error(), "failed validation") {
		t.Errorf("error should mention failed validation: %v", err)
	}
	if _, statErr := os.Stat("out"); statErr == nil {
		t.Error("check should not have written output despite reporting per-entry")
	}
}

func TestRunCheckFromConfig_noConfig_errors(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	err := runCheckFromConfig(build.Options{})
	if err == nil {
		t.Fatal("expected error when no litprompt.yaml exists, got nil")
	}
	if !strings.Contains(err.Error(), "litprompt.yaml") {
		t.Errorf("error should mention litprompt.yaml: %v", err)
	}
}

func TestRunCheckFromConfig_explicitConfigInOtherDir(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	// Config and source live in envs/, not the cwd. Sources resolve relative to
	// the config's directory, so a source named relative to it must be found.
	writeTestFile(t, "envs/agent.md", "# agent\n")
	writeTestFile(t, "envs/litprompt.prod.yaml", `builds:
  - source: agent.md
    output: dist/agent.md
`)

	configPath = "envs/litprompt.prod.yaml"
	defer func() { configPath = "" }()

	if err := runCheckFromConfig(build.Options{}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Check writes nothing, in either directory.
	if _, err := os.Stat(filepath.Join(dir, "envs/dist")); err == nil {
		t.Error("check should not have written output relative to config dir")
	}
}

func TestRunCheckFromConfig_explicitConfigMissing_errors(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	configPath = "litprompt.prod.yaml"
	defer func() { configPath = "" }()

	err := runCheckFromConfig(build.Options{})
	if err == nil {
		t.Fatal("expected error for missing named config, got nil")
	}
	if !strings.Contains(err.Error(), "litprompt.prod.yaml") {
		t.Errorf("error should name the missing config: %v", err)
	}
}

func TestRunCheckFromConfig_restoresCwd(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	// A config in a subdirectory triggers an internal chdir; the process cwd
	// must be back where it started once the check returns.
	writeTestFile(t, "envs/agent.md", "# agent\n")
	writeTestFile(t, "envs/litprompt.prod.yaml", `builds:
  - source: agent.md
    output: dist/agent.md
`)

	configPath = "envs/litprompt.prod.yaml"
	defer func() { configPath = "" }()

	before, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := runCheckFromConfig(build.Options{}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	after, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if before != after {
		t.Errorf("working directory not restored: before %q, after %q", before, after)
	}
}

func TestRunCheck_configFlagWithSourceArg_errors(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	writeTestFile(t, "prompt.md", "# hi\n")

	configPath = "litprompt.prod.yaml"
	defer func() { configPath = "" }()

	err := runCheck(nil, []string{"prompt.md"})
	if err == nil {
		t.Fatal("expected error combining --config with a source argument, got nil")
	}
	if !strings.Contains(err.Error(), "--config") {
		t.Errorf("error should mention --config: %v", err)
	}
}

func TestRunBuildFromConfig_restoresCwd(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	// A config in a subdirectory triggers an internal chdir; the process cwd
	// must be back where it started once the build returns.
	writeTestFile(t, "envs/agent.md", "# agent\n")
	writeTestFile(t, "envs/litprompt.prod.yaml", `builds:
  - source: agent.md
    output: dist/agent.md
`)

	configPath = "envs/litprompt.prod.yaml"
	defer func() { configPath = "" }()

	before, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := runBuildFromConfig(build.Options{}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	after, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if before != after {
		t.Errorf("working directory not restored: before %q, after %q", before, after)
	}
}
